### ISSUE TITLE
Nested scrolling problem

### ISSUE THREAD

**Issue by MFlisar** [BelooS/ChipsLayoutManager#16] opened 2016-12-05 07:45 UTC
Seems like it's the `LayoutManagers` responsibility to handle nested scrolling somehow, because placing a `LinearLayoutManager` inside a `BottomSheetDialogFragment` works like a charm but if I use `ChipsLayoutManager` and try to scroll down the list the `BottomSheet` is closed...

It needs to consume the scroll events somehow it seems...

**Comment by BelooS** [comment] 2016-12-05 09:13
I'll check that

**Comment by BelooS** [comment] 2016-12-05 14:51
Seems i could resolve it. To find an answer i have researched `LinearLayoutManager` code, seems that if `RecyclerView` is docked to another scrollable container - it draws whole available items, no matter how much are them without any recycling and this is a feature for such types of containers. (`LinearLayoutManager` has `boolean resolveIsInfinite()` method). So i'm going to implement such behaviour in my lm.

**Comment by BelooS** [comment] 2016-12-05 16:05
fixed in v0.3.2

**Comment by MFlisar** [comment] 2016-12-05 20:05
Tried it in a `BottomSheetDialogFragment` but it does not work.

If the `RecylcerView` has only a few items, I can't close the dialog, if it has many items, I can't scroll and the dialog always directly closes when trying to scroll...

**Comment by BelooS** [comment] 2016-12-06 08:23
Could you check `BottomSheetDialogFragment` in a sample and tell where should i change the code to reproduce an issue? I've tried with few or many items.

**Comment by BelooS** [comment] 2016-12-19 13:46
I've closed it, due to in the last version logic seems to be correct, but feel free to comment in case any update.

**Closed by BelooS** 2016-12-19 13:46 UTC
Labels: bug, Ready

**Comment by csbenz** [comment] 2017-02-13 04:02
I'm having the same issue. No problem with other LayoutManagers, but ChipsLayoutManager seems to disable scrolling completely.

**Comment by csbenz** [comment] 2017-02-13 04:05
Sorry, it was a mistake in my code :)
